### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by Bentipe** [InfectoOne/vue-ganttastic#6]
Is there a way to implement horizontal scrolling?

**Comment by fabionixweb** [comment]
wrap gantt in a div and apply css

.scroll-gantt {
  display: flex !important;
  flex-wrap: nowrap !important;
  overflow: auto;
  overflow-y: hidden;
}

**Comment by Praveenstein** [comment]
> wrap gantt in a div and apply css
> 
> .scroll-gantt { display: flex !important; flex-wrap: nowrap !important; overflow: auto; overflow-y: hidden; }

The problem with this is, the header, which consist of the timeline is not rendered, if the number of task goes beyond the current horizontal view

**Comment by YUN-RU-TSENG** [comment]
same issue

**Comment by RufusMotus** [comment]
```html
<div class='wrapper'>
  <g-gantt-chart></g-gantt-chart>
</div>
```

```css
.wrapper {
  height: 100vh //change accordingly;
  width: 100vw //change accordingly;
  overflow-x: auto;
}

:deep(.g-gantt-chart) {
  height: 100%;
  width: max-content !important;
  min-width: 100%;
}
```
